language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk7

after_success:
  - ./publish/deploy.sh

env:
  global:
  - secure: tsVaUgGMWTYNUGl2HNmpIQyT0l15VGbmr4TPURvzz1pRaq49+sBM0xnz5zP0q198eeT7ff/bKmftDvLAQDOu5B8HfnQnfqac2sLh0ujtW1gq2M0ueCWcYQOtd7dLngbU/1MCXTNOgDqtUACxV30yNpKJiMMM7MV5RKtnxJ6JhuwEXtcaN2HyOtjdqytKdyGbtGTfFaJH3vy87en+6HAMGj9xpFEVlhJCdvAfSXutNPNAqN1RlAAJu3FLnddKSlDQfK8I0AnjgYyN7TKCqe6vMcVTfoA3S6Vwt2Fjtvm4S5EYUBC11hFeGmQg7fSRHakWvH/+sbBQNyzVUxTzcnOpbHhl+CbHfZO+avNPR9/71c6t6acPPFtYCc6PRgAafe2Cx8Cs+plVhHjNoexmXjf6adu2MVFcuertazlBFqfEE8tSG59XhQZxeVMsMw5r1bfXN4PbVCq6Uc6SgtNlbw8VnJ8kkpNENPUusjrN7wfUdR3jbcbqAftZUjmKzaTBBJAgRLOjrWMLndbfHd/UJRRkGQsfvZ0ArymylWTRoVgcB9DRwE10BMF4Zj8XR+3baet/SM/5ho2AJE7czuH+MtrPPZcTgmbKo+0Oxvc26sJXqZFHxLZJ7sPq1IDkv5xiLhW61plKbvPRG4rA+7qv0fPSS3TpKXAqpj8/mRTjhkMk67Q=
  - secure: Z3mGbV2GvL32sTDM9ToX6ZSBhd6rY+a1xx3Ytjp9bwU1i26nZ/tYHfhLdOIamX/5gdbtSsI/cnezywgMPcL0dTiz+n3VoWrRB7Z3idv3GX2TzWjKWH0kxbFCtJZP9t5aK2yRwZ54Gbq/Wuz1yMNTXOP6THml0vkgxIA7EVB6HAFwf8pnvE3c5fQR/Nzq9z/EyPs3Fb+hIi+PqHXH7EXwyt3Vv5MtQ8ifSULhmps1skQjbFvnjlRRDvDWvIPLUtriajRx0Cg6o2CEIufGo5/MEqy+Ed9ewds5CUD8gVB4UEDB4gfHdBU+6qHtDpYeZ4KaXCLb6GaTP5PK8vO3z97Ehtp0CQXRnch4WDZC06jbyfF153b49KTBzPPYNv52eLsKEo5nvUbo54A9bepbe2KKwJR/Dy+QmNZ4YMwZgHJay70vYcga/XidB5K5nwPh5iu8ODR/ubD5rFyf6k+0SzcXr9JECk4RwWkJiflp+Lvz5OLA1Mo7cvF3RdgcYS/INmoxgXrZqzagftjVYgh39799+l9k+vEvFCpl91n25gTwoqfLakQDM7uU0yURezs7qkL7iH4Zo7cf5iLPhgFHP3zC62eEh0kBhR6Ojr+rknwETGr/AEmxYX9USlQrOyTBMs15vCQ6dJFtpffz64IcSbtDyVhZ92ayEQcYQkZw+wFfSOc=
